create table if not exists player_feature_snapshots (
    id bigint generated by default as identity primary key,
    snapshot_time timestamp not null,
    game_id bigint not null,
    player_id bigint not null,
    team_id bigint,
    generated_at timestamp not null default current_timestamp,
    data_cutoff_time timestamp not null,
    model_version_id bigint,
    features varchar(4000) not null,
    unique (snapshot_time, game_id, player_id)
);

create table if not exists data_source_logs (
    id bigint generated by default as identity primary key,
    source_name varchar(1000) not null,
    source_type varchar(255) not null,
    source_path varchar(1000),
    ingested_at timestamp not null default current_timestamp,
    status varchar(255) not null,
    records_processed integer not null default 0,
    notes varchar(4000)
);

create table if not exists refresh_logs (
    id bigint generated by default as identity primary key,
    refresh_type varchar(255) not null,
    started_at timestamp not null default current_timestamp,
    finished_at timestamp,
    status varchar(255) not null,
    records_processed integer not null default 0,
    error_message varchar(4000)
);

create table if not exists team_feature_snapshots (
    id bigint generated by default as identity primary key,
    snapshot_time timestamp not null,
    game_id bigint not null,
    team_id bigint not null,
    generated_at timestamp not null default current_timestamp,
    data_cutoff_time timestamp not null,
    model_version_id bigint,
    features varchar(4000) not null,
    unique (snapshot_time, game_id, team_id)
);

create table if not exists game_feature_snapshots (
    id bigint generated by default as identity primary key,
    snapshot_time timestamp not null,
    game_id bigint not null,
    generated_at timestamp not null default current_timestamp,
    data_cutoff_time timestamp not null,
    model_version_id bigint,
    features varchar(4000) not null,
    unique (snapshot_time, game_id)
);

create table if not exists model_versions (
    id bigint generated by default as identity primary key,
    version_name varchar(255) not null unique,
    model_type varchar(255) not null,
    target_variable varchar(255) not null,
    trained_at timestamp,
    training_data_start date,
    training_data_end date,
    feature_set_version varchar(255),
    artifact_path varchar(1000),
    status varchar(255) not null default 'candidate',
    is_active boolean not null default false,
    created_at timestamp not null default current_timestamp
);

create table if not exists model_metrics (
    id bigint generated by default as identity primary key,
    model_version_id bigint,
    target_variable varchar(255) not null,
    mae numeric(10,4),
    rmse numeric(10,4),
    r2_score numeric(10,4),
    validation_sample_size integer,
    evaluated_at timestamp not null default current_timestamp
);

create table if not exists model_training_runs (
    id bigint generated by default as identity primary key,
    started_at timestamp not null default current_timestamp,
    finished_at timestamp,
    status varchar(255) not null,
    training_data_range varchar(255),
    validation_data_range varchar(255),
    triggered_by varchar(255),
    notes varchar(4000)
);

create table if not exists model_registry (
    id bigint generated by default as identity primary key,
    model_version_id bigint not null,
    registry_status varchar(255) not null,
    registered_at timestamp not null default current_timestamp,
    archived_at timestamp
);

create table if not exists prediction_actuals (
    id bigint generated by default as identity primary key,
    prediction_id bigint not null,
    actual_value varchar(4000) not null,
    recorded_at timestamp not null default current_timestamp
);

create table if not exists prediction_errors (
    id bigint generated by default as identity primary key,
    prediction_id bigint not null,
    target_variable varchar(255) not null,
    predicted_value numeric(10,4),
    actual_value numeric(10,4),
    absolute_error numeric(10,4),
    squared_error numeric(12,4),
    recorded_at timestamp not null default current_timestamp
);

create table if not exists model_promotion_history (
    id bigint generated by default as identity primary key,
    previous_model_version_id bigint,
    candidate_model_version_id bigint,
    promoted boolean not null,
    reason varchar(4000) not null,
    previous_mae numeric(10,4),
    candidate_mae numeric(10,4),
    promoted_at timestamp not null default current_timestamp
);

create table if not exists team_strength_ratings (
    id bigint generated by default as identity primary key,
    season_start_year integer not null,
    team_id bigint not null,
    source_season_start_year integer,
    rating numeric(8,4) not null,
    base_win_percentage numeric(8,4),
    point_differential numeric(8,4),
    roster_impact_score numeric(8,4),
    injury_risk_score numeric(8,4),
    generated_at timestamp not null default current_timestamp,
    explanation varchar(4000),
    unique (season_start_year, team_id)
);

create table if not exists standings_projections (
    id bigint generated by default as identity primary key,
    season_start_year integer not null,
    team_id bigint not null,
    conference varchar(255),
    projected_wins numeric(6,2) not null,
    projected_losses numeric(6,2) not null,
    low_wins numeric(6,2),
    median_wins numeric(6,2),
    high_wins numeric(6,2),
    projected_seed integer,
    playoff_probability numeric(6,4),
    projection_method varchar(255) not null,
    schedule_available boolean not null default false,
    generated_at timestamp not null default current_timestamp,
    top_reasons varchar(4000),
    uncertainty_factors varchar(4000),
    unique (season_start_year, team_id)
);

create table if not exists season_simulation_runs (
    id bigint generated by default as identity primary key,
    season_start_year integer not null,
    run_count integer not null,
    schedule_available boolean not null default false,
    generated_at timestamp not null default current_timestamp,
    notes varchar(4000)
);

create table if not exists projected_team_records (
    id bigint generated by default as identity primary key,
    simulation_run_id bigint not null,
    team_id bigint not null,
    expected_wins numeric(6,2) not null,
    expected_losses numeric(6,2) not null,
    low_wins numeric(6,2),
    median_wins numeric(6,2),
    high_wins numeric(6,2),
    conference_seed integer,
    playoff_probability numeric(6,4)
);

create table if not exists roster_change_events (
    id bigint generated by default as identity primary key,
    season_start_year integer not null,
    team_id bigint,
    player_id bigint,
    event_type varchar(255) not null,
    impact_score numeric(8,4),
    event_date date,
    source varchar(255),
    notes varchar(4000),
    ingested_at timestamp not null default current_timestamp
);

create table if not exists team_context_snapshots (
    id bigint generated by default as identity primary key,
    season_start_year integer not null,
    team_id bigint not null,
    snapshot_date date not null default current_date,
    roster_turnover_score numeric(8,4),
    injury_risk_score numeric(8,4),
    team_strength_rating numeric(8,4),
    context_summary varchar(4000),
    generated_at timestamp not null default current_timestamp,
    unique (season_start_year, team_id, snapshot_date)
);

create table if not exists predictions (
    id bigint generated by default as identity primary key,
    prediction_type varchar(255) not null,
    game_id bigint,
    player_id bigint,
    team_id bigint,
    model_version_id bigint,
    requested_at timestamp not null default current_timestamp,
    data_cutoff_time timestamp,
    input_fingerprint varchar(255),
    confidence_score numeric(6,4),
    explanation varchar(4000) not null default '[]'
);

create table if not exists player_stat_predictions (
    prediction_id bigint primary key,
    projected_points numeric(6,2),
    projected_rebounds numeric(6,2),
    projected_assists numeric(6,2),
    projected_steals numeric(6,2),
    projected_blocks numeric(6,2),
    projected_turnovers numeric(6,2),
    projected_minutes numeric(6,2),
    projected_field_goal_percentage numeric(6,4)
);

create table if not exists team_score_predictions (
    prediction_id bigint primary key,
    home_team_id bigint,
    away_team_id bigint,
    home_team_score numeric(6,2),
    away_team_score numeric(6,2),
    predicted_winner_team_id bigint,
    point_differential numeric(6,2)
);

create table if not exists fantasy_predictions (
    prediction_id bigint primary key,
    fantasy_points numeric(6,2),
    floor_projection numeric(6,2),
    ceiling_projection numeric(6,2),
    risk_level varchar(255),
    scoring_formula varchar(4000) not null default '{}'
);

create table if not exists roster_snapshots (
    id bigint generated by default as identity primary key,
    snapshot_date date not null,
    team_id bigint not null,
    player_id bigint not null,
    position varchar(255),
    roster_status varchar(255),
    projected_minutes numeric(5,2),
    source varchar(255),
    ingested_at timestamp not null default current_timestamp,
    unique (snapshot_date, team_id, player_id)
);

create table if not exists transactions (
    id bigint generated by default as identity primary key,
    player_id bigint,
    from_team_id bigint,
    to_team_id bigint,
    transaction_type varchar(255) not null,
    transaction_date date,
    source varchar(255),
    source_url varchar(1000),
    source_status varchar(255) not null default 'official',
    confidence numeric(5,4) not null default 1.0000,
    affects_projection boolean not null default true,
    reported_at timestamp,
    notes varchar(4000),
    ingested_at timestamp not null default current_timestamp
);

create table if not exists draft_picks (
    id bigint generated by default as identity primary key,
    player_id bigint,
    team_id bigint,
    draft_year integer not null,
    draft_round integer,
    draft_number integer,
    rookie_season_start_year integer
);

create table if not exists injury_reports (
    id bigint generated by default as identity primary key,
    report_date date not null,
    game_date date,
    team_id bigint,
    player_id bigint,
    injury_status varchar(255) not null,
    reason varchar(4000),
    source varchar(255),
    confidence numeric(5,4),
    valid_until timestamp,
    scraped_at timestamp not null default current_timestamp,
    ingested_at timestamp not null default current_timestamp
);

create table if not exists player_advanced_stats (
    id bigint generated by default as identity primary key,
    player_id bigint not null,
    team_id bigint,
    season_start_year integer,
    game_id bigint,
    usage_percentage numeric(8,4),
    source varchar(255),
    ingested_at timestamp not null default current_timestamp
);

delete from player_advanced_stats;
delete from data_source_logs;
delete from refresh_logs;
delete from injury_reports;
delete from draft_picks;
delete from transactions;
delete from roster_snapshots;
delete from model_promotion_history;
delete from projected_team_records;
delete from season_simulation_runs;
delete from standings_projections;
delete from team_strength_ratings;
delete from roster_change_events;
delete from team_context_snapshots;
delete from prediction_errors;
delete from prediction_actuals;
delete from model_registry;
delete from model_training_runs;
delete from model_metrics;
delete from fantasy_predictions;
delete from team_score_predictions;
delete from player_stat_predictions;
delete from predictions;
delete from model_versions;
delete from game_feature_snapshots;
delete from team_feature_snapshots;
delete from player_feature_snapshots;
delete from player_game_stats;
delete from team_game_stats;
delete from games;
delete from players;
delete from teams;
