create table if not exists player_feature_snapshots (
    id bigint generated by default as identity primary key,
    snapshot_time timestamp not null,
    game_id bigint not null,
    player_id bigint not null,
    team_id bigint,
    generated_at timestamp not null default current_timestamp,
    data_cutoff_time timestamp not null,
    model_version_id bigint,
    features varchar(4000) not null,
    unique (snapshot_time, game_id, player_id)
);

create table if not exists team_feature_snapshots (
    id bigint generated by default as identity primary key,
    snapshot_time timestamp not null,
    game_id bigint not null,
    team_id bigint not null,
    generated_at timestamp not null default current_timestamp,
    data_cutoff_time timestamp not null,
    model_version_id bigint,
    features varchar(4000) not null,
    unique (snapshot_time, game_id, team_id)
);

create table if not exists game_feature_snapshots (
    id bigint generated by default as identity primary key,
    snapshot_time timestamp not null,
    game_id bigint not null,
    generated_at timestamp not null default current_timestamp,
    data_cutoff_time timestamp not null,
    model_version_id bigint,
    features varchar(4000) not null,
    unique (snapshot_time, game_id)
);

create table if not exists model_versions (
    id bigint generated by default as identity primary key,
    version_name varchar(255) not null unique,
    model_type varchar(255) not null,
    target_variable varchar(255) not null,
    status varchar(255) not null default 'candidate',
    is_active boolean not null default false,
    created_at timestamp not null default current_timestamp
);

create table if not exists predictions (
    id bigint generated by default as identity primary key,
    prediction_type varchar(255) not null,
    game_id bigint,
    player_id bigint,
    team_id bigint,
    model_version_id bigint,
    requested_at timestamp not null default current_timestamp,
    data_cutoff_time timestamp,
    input_fingerprint varchar(255),
    confidence_score numeric(6,4),
    explanation varchar(4000) not null default '[]'
);

create table if not exists player_stat_predictions (
    prediction_id bigint primary key,
    projected_points numeric(6,2),
    projected_rebounds numeric(6,2),
    projected_assists numeric(6,2),
    projected_steals numeric(6,2),
    projected_blocks numeric(6,2),
    projected_turnovers numeric(6,2),
    projected_minutes numeric(6,2),
    projected_field_goal_percentage numeric(6,4)
);

create table if not exists team_score_predictions (
    prediction_id bigint primary key,
    home_team_id bigint,
    away_team_id bigint,
    home_team_score numeric(6,2),
    away_team_score numeric(6,2),
    predicted_winner_team_id bigint,
    point_differential numeric(6,2)
);

create table if not exists fantasy_predictions (
    prediction_id bigint primary key,
    fantasy_points numeric(6,2),
    floor_projection numeric(6,2),
    ceiling_projection numeric(6,2),
    risk_level varchar(255),
    scoring_formula varchar(4000) not null default '{}'
);

create table if not exists roster_snapshots (
    id bigint generated by default as identity primary key,
    snapshot_date date not null,
    team_id bigint not null,
    player_id bigint not null,
    position varchar(255),
    roster_status varchar(255),
    projected_minutes numeric(5,2),
    source varchar(255),
    ingested_at timestamp not null default current_timestamp,
    unique (snapshot_date, team_id, player_id)
);

create table if not exists transactions (
    id bigint generated by default as identity primary key,
    player_id bigint,
    from_team_id bigint,
    to_team_id bigint,
    transaction_type varchar(255) not null,
    transaction_date date,
    source varchar(255),
    notes varchar(4000),
    ingested_at timestamp not null default current_timestamp
);

create table if not exists draft_picks (
    id bigint generated by default as identity primary key,
    player_id bigint,
    team_id bigint,
    draft_year integer not null,
    draft_round integer,
    draft_number integer,
    rookie_season_start_year integer
);

create table if not exists injury_reports (
    id bigint generated by default as identity primary key,
    report_date date not null,
    game_date date,
    team_id bigint,
    player_id bigint,
    injury_status varchar(255) not null,
    reason varchar(4000),
    source varchar(255),
    confidence numeric(5,4),
    valid_until timestamp,
    scraped_at timestamp not null default current_timestamp,
    ingested_at timestamp not null default current_timestamp
);

create table if not exists player_advanced_stats (
    id bigint generated by default as identity primary key,
    player_id bigint not null,
    team_id bigint,
    season_start_year integer,
    game_id bigint,
    usage_percentage numeric(8,4),
    source varchar(255),
    ingested_at timestamp not null default current_timestamp
);

delete from player_advanced_stats;
delete from injury_reports;
delete from draft_picks;
delete from transactions;
delete from roster_snapshots;
delete from fantasy_predictions;
delete from team_score_predictions;
delete from player_stat_predictions;
delete from predictions;
delete from model_versions;
delete from game_feature_snapshots;
delete from team_feature_snapshots;
delete from player_feature_snapshots;
delete from player_game_stats;
delete from team_game_stats;
delete from games;
delete from players;
delete from teams;
