create table if not exists player_feature_snapshots (
    id bigint generated by default as identity primary key,
    snapshot_time timestamp not null,
    game_id bigint not null,
    player_id bigint not null,
    team_id bigint,
    generated_at timestamp not null default current_timestamp,
    data_cutoff_time timestamp not null,
    model_version_id bigint,
    features varchar(4000) not null,
    unique (snapshot_time, game_id, player_id)
);

delete from player_feature_snapshots;
delete from player_game_stats;
delete from team_game_stats;
delete from games;
delete from players;
delete from teams;
